name: stryd-sync-garmin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,19 * * ?'
env:
  GITHUB_NAME: yangxun
  GITHUB_EMAIL: yangxun@outlook.com
  ## 佳明配置
  GARMIN_AUTH_DOMAIN: ${{ secrets.GARMIN_AUTH_DOMAIN }}
  GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}

  ## Stryd配置
  STRYD_EMAIL: ${{ secrets.STRYD_EMAIL }}
  STRYD_PASSWORD: ${{ secrets.STRYD_PASSWORD }}  
  

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.2"
    # from pdm
    - name: Set Variables
      id: set_variables
      run: |
        echo "::set-output name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"        
    - name: Cache PIP
      uses: actions/cache@v3
      with:
        path: ${{ steps.set_variables.outputs.PIP_CACHE }}
        key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
      if: steps.pip-cache.outputs.cache-hit != 'true'
    - name: Run Stryd Sync Garmin
      run: |
        python scripts/stryd/stryd_sync_connect.py        
    - name: Push new Activity
      run: |
        git config --local user.email "${{ env.GITHUB_EMAIL }}"
        git config --local user.name "${{ env.GITHUB_NAME }}"
        git add .
        git commit -m 'update garmin cookie' || echo "nothing to commit"
        git push || echo "nothing to push"        
